# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x02\x61i\"\xca\x01\n\x12\x41udioStreamRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x12\x11\n\tcall_type\x18\x05 \x01(\t\x12\x14\n\x0c\x61udio_format\x18\x06 \x01(\t\x12\x13\n\x0bsample_rate\x18\x07 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x08 \x01(\x05\x12\x17\n\x0f\x62its_per_sample\x18\t \x01(\x05\"\xe9\x01\n\x13\x41udioStreamResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\x16\n\x0e\x61udio_response\x18\x03 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x10\n\x08metadata\x18\x05 \x01(\t\x12\x1d\n\x15response_audio_format\x18\x06 \x01(\t\x12\x1c\n\x14response_sample_rate\x18\x07 \x01(\x05\x12\x19\n\x11response_channels\x18\x08 \x01(\x05\x12\x18\n\x10\x63onfidence_score\x18\t \x01(\x02\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa8\x01\n\x13HealthCheckResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.ai.HealthCheckResponse.HealthStatus\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"9\n\x0cHealthStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\x98\x01\n\tAIService\x12K\n\x14ProcessRealTimeAudio\x12\x16.ai.AudioStreamRequest\x1a\x17.ai.AudioStreamResponse(\x01\x30\x01\x12>\n\x0bHealthCheck\x12\x16.ai.HealthCheckRequest\x1a\x17.ai.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOSTREAMREQUEST']._serialized_start=25
  _globals['_AUDIOSTREAMREQUEST']._serialized_end=227
  _globals['_AUDIOSTREAMRESPONSE']._serialized_start=230
  _globals['_AUDIOSTREAMRESPONSE']._serialized_end=463
  _globals['_HEALTHCHECKREQUEST']._serialized_start=465
  _globals['_HEALTHCHECKREQUEST']._serialized_end=502
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=505
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=673
  _globals['_HEALTHCHECKRESPONSE_HEALTHSTATUS']._serialized_start=616
  _globals['_HEALTHCHECKRESPONSE_HEALTHSTATUS']._serialized_end=673
  _globals['_AISERVICE']._serialized_start=676
  _globals['_AISERVICE']._serialized_end=828
# @@protoc_insertion_point(module_scope)
